"""Task contract — lightweight scope + guardrails for each task execution.

Generated by EA when routing a task. Stored as YAML in
company/business/contracts/{task_id}.yaml.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


class TaskContract(BaseModel):
    """Scope definition and guardrails for a task, generated by EA before execution."""
    task_id: str
    title: str

    # Intent (EA parses CEO input)
    goals: list[str]
    constraints: list[str] = []

    # Scope
    assigned_agent: str = ""
    allowed_tools: list[str] = []
    protected_paths: list[str] = Field(
        default_factory=lambda: [".env", "config.yaml", "company/human_resource/"]
    )

    # Guardrails
    max_cost_usd: float = 1.0
    max_iterations: int = 5
    require_ceo_approval: bool = False
    risk_level: Literal["low", "medium", "high"] = "low"

    # Acceptance
    acceptance_criteria: list[str] = []
    verification_commands: list[str] = []

    created_at: datetime = Field(default_factory=datetime.now)
